=== kkmarv/IOTA-Digital-Student-ID/schemas/person.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "National ID Card",
  "description": "A national ID card is a government-issued document used for personal identification.",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "firstNames": {
      "type": "array",
      "description": "The first names of the cardholder.",
      "items": {
        "type": "string"
      }
    },
    "lastName": {
      "type": "string",
      "description": "The full name of the cardholder."
    },
    "nationality": {
      "type": "string",
      "description": "The country or nation to which the cardholder is considered a citizen."
    },
    "dateOfBirth": {
      "type": "string",
      "format": "date",
      "description": "The date on which the cardholder was born."
    },
    "placeOfBirth": {
      "type": "string",
      "description": "The city where the cardholder was born."
    },
    "biometricPhotoURI": {
      "type": "string",
      "format": "uri",
      "description": "A URI that points to a biometric picture of the cardholder."
    },
    "address": {
      "$ref": "address.json"
    }
  },
  "required": ["firstNames", "lastName", "nationality", "dateOfBirth", "placeOfBirth", "biometricPhotoURI", "address"]
}

=== kkmarv/IOTA-Digital-Student-ID/examples/person.json
{
  "$schema": "../schemas/person.json",
  "firstNames": ["Walter", "Hartwell"],
  "lastName": "White",
  "dateOfBirth": "1959-09-07",
  "placeOfBirth": "Albuquerque, New Mexico",
  "nationality": "United States of America",
  "address": {
    "houseNumber": 308,
    "street": "Negra Arroyo Lane",
    "postalCode": "87104",
    "city": "Albuquerque",
    "state": "New Mexico",
    "country": "United States of America"
  },
  "biometricPhotoURI": "https://vignette.wikia.nocookie.net/breakingbad/images/e/e7/BB-S5B-Walt-590.jpg/revision/latest?cb=20130928055404"
}
